version: '3'

services:
  backend:
    container_name: hackathon-server
    depends_on:
      - mongodb
    env_file:
        "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped # set to always for deployment
  frontend:
    container_name: hackathon-frontend
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped # set to always for deployment
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "20717:20717"
    restart: unless-stopped
    volumes:
      - db:/data/db # Create a volume for the DB.

volumes:
  db: