version: '3'

services:
  backend:
    container_name: hackathon-server
    depends_on:
      - mongo
    # env_file:
    #     "./server/server.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped # set to always for deployment  
  frontend:
    container_name: hackathon-frontend
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped # set to always for deployment
  mongo:
    image: mongo:latest
    ports:
      - "20717:20717"
    volumes:
      - /data/db # Create a volume for the DB.    